Mobile/Models/AllocationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

using Planetshakers.Core.Models;

namespace Planetshakers.Events.Models
{
    public class AllocationViewModel
    {
        public int Contact_ID { get; set; }
        public string ContactName
        {
            get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var name = (from cc in context.Common_Contact
                                where cc.Contact_ID == Contact_ID
                                select cc.FirstName + " " + cc.LastName).FirstOrDefault();

                    return name;
                }
            }
        }

        public int Registration_ID { get; set; }     

        [Display(Name = "Event")]
        public int Venue_ID { get; set; }

        public int Conference_ID { get; set; }

        public string ConferenceName
        {
            get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var name = (from ev in context.Events_Venue
                                join ec in context.Events_Conference
                                    on ev.Conference_ID equals ec.Conference_ID
                                where ev.Venue_ID == Venue_ID
                                select ec.ConferenceName).FirstOrDefault();

                    return name;
                }
            }
        }

        private List<EventModel> _events
        {
            get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var _events = (from ec in context.Events_Conference
                                   join ev in context.Events_Venue
                                   on ec.Conference_ID equals ev.Conference_ID
                                   orderby ev.ConferenceStartDate descending, Venue_ID ascending
                                   select new EventModel
                                   {
                                       VenueID = ev.Venue_ID,
                                       ConferenceName = ec.ConferenceName
                                   }).ToList();

                    return _events;
                }
            }
        }

        public IEnumerable<SelectListItem> EventList { get { return new SelectList(_events, "VenueID", "ConferenceName"); } }

        public List<ContactDetails> searchList { get; set; }

        public int RegistrationType_ID { get; set; }
        public string RegistrationType
        {
            get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var name = (from ert in context.Events_RegistrationType
                                where ert.RegistrationType_ID == RegistrationType_ID
                                select ert.RegistrationType).FirstOrDefault();

                    return name;
                }
            }
        }

        public List<UnallocatedRegistration> unallocatedRegoList
        {
            get
            {
                var unallocated_regos = new List<UnallocatedRegistration>();

                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var list = (from egbr in context.Events_GroupBulkRegistration
                                where egbr.GroupLeader_ID == Contact_ID
                                        && egbr.Venue_ID == Venue_ID
                                select egbr).ToList();
                    


                    foreach (var item in list)
                    {
                        var unallocated = new UnallocatedRegistration();

                        unallocated.GroupLeader_ID = item.GroupLeader_ID;
                        unallocated.Venue_ID = item.Venue_ID;

                        unallocated.GroupLeader = (from eg in context.Events_Group
                                                    where eg.GroupLeader_ID == item.GroupLeader_ID
                                                    select eg.GroupName).FirstOrDefault();

                        unallocated.RegistrationType_ID = item.RegistrationType_ID;

                        unallocated.RegistrationType = (from ert in context.Events_RegistrationType
                                                         where ert.RegistrationType_ID == item.RegistrationType_ID
                                                         select ert.RegistrationType).FirstOrDefault();

                        unallocated.Venue_ID = item.Venue_ID;
                        //unallocated.Allocated = (int) item.Allocated;
                        //unallocated.Unallocated = (int) item.UnAllocated;

                        unallocated_regos.Add(unallocated);
                    }

                    return unallocated_regos;                    
                }
            }
        }

        public int TotalUnallocated
        {
            get
            {
                return this.unallocatedRegoList.Sum(x => x.Unallocated);
            }
        }

        public int TotalAllocated
        {
            get
            {
                return this.unallocatedRegoList.Sum(x => x.Allocated);
            }
        }

        public List<Registration> AllocatedRegoList
        {
            get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var list = (from er in context.Events_Registration
                                join cc in context.Common_Contact
                                    on er.Contact_ID equals cc.Contact_ID
                                where er.GroupLeader_ID == Contact_ID && er.Venue_ID == this.Venue_ID
                                select new Registration
                                {
                                    ID = er.Registration_ID,
                                    FirstName = cc.FirstName,
                                    LastName = cc.LastName,
                                    Mobile = cc.Mobile,
                                    Email = (cc.Email == String.Empty ? cc.Email2 : cc.Email)
                                }).ToList();

                    return list;
                }                
            }
        }

        public List<SelectListItem> AvailableRegistrationTypeList
        {
            get
            {
                var list = unallocatedRegoList.Where(x => x.Unallocated >= 1).ToList();

                var selectlist = new List<SelectListItem>();

                foreach (var i in list)
                    selectlist.Add(new SelectListItem { Text=i.RegistrationType, Value=i.RegistrationType_ID.ToString() });

                return selectlist;
            }
        }
        
        public string SelectedOption { get; set; }
        public List<SelectListItem> AllocateOption
        {
            get
            {
                var selectlist = new List<SelectListItem> {
                    new SelectListItem{ Text="Existing", Value="Existing" },
                    new SelectListItem{ Text="New", Value="New" }
                };

                return selectlist;
            }
        }

        public int Allocation_ID { get; set; }

        public string SuccessMessage { get; set; }
        
        [Display(Name = "First Name")]
        public string NewFirstName { get; set; }

        [Display(Name = "Last Name")]
        public string NewLastName { get; set; }

        [Display(Name = "Mobile")]
        public string NewMobile { get; set; }

        [Display(Name = "Email")]
        public string NewEmail { get; set; }

        [Display(Name = "Attended?")]
        public bool NewAttended { get; set; }
    }
}

Mobile/Controllers/AdministrationController.cs
using log4net;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Web.Mvc;
using Planetshakers.Core.Models;
using Planetshakers.Events.Models;
using Planetshakers.Events.Security;
using Planetshakers.Core.DataInterfaces;
using Stripe;
using SelectPdf;
using System.Web;
using System.IO;
using System.Text;
using System.Data.SqlClient;
using System.Configuration;
using Stripe.Checkout;
using System.Data.Entity;
using FlexCel.XlsAdapter;

namespace Planetshakers.Events.Controllers
{
    [Authorize]
    public class AdministrationController : Controller
    {
        private readonly IAdministrationRepository _repository;

        public AdministrationController(IAdministrationRepository repository)
        {
            _repository = repository;
        }

        public ActionResult RegistrationAdminIndex()
        {
            return View();
        }

        #region Conference Registrations

        public ActionResult Registrations()
        {
            var model = new PurchaseViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult SearchContact(string query)
        {
            if (query != null)
            {
                int i;

                if (query.Length < 3)
                {
                    ViewBag.Message = "Query is too short. Please provide the full name or full email.";
                    return View("Error");
                }

                if (int.TryParse(query, out i))
                {
                    ViewBag.Message = "Invalid query. Please search by full name or full email.";
                    return View("Error");
                }

                try
                {
                    var model = new PurchaseViewModel();

                    using (PlanetshakersEntities context = new PlanetshakersEntities())
                    {
                        model.searchList = new List<ContactDetails>();

                        // Search for names with spaces
                        if (query.Contains(" "))
                        {
                            var substrings = query.ToLower().Split();

                            var list = (from cc in context.Common_Contact
                                        where (cc.FirstName + " " + cc.LastName == query || cc.LastName + " " + cc.FirstName == query)
                                        select new ContactDetails
                                        {
                                            Id = cc.Contact_ID,
                                            FirstName = cc.FirstName,
                                            LastName = cc.LastName,
                                            ContactNumber = cc.Mobile,
                                            Email = cc.Email
                                        }).ToList();

                            model.searchList.AddRange(list);

                            foreach (var s in substrings)
                            {
                                list = (from cc in context.Common_Contact
                                        where (cc.FirstName.StartsWith(s.ToLower()) || cc.LastName.StartsWith(s.ToLower()))
                                        select new ContactDetails
                                        {
                                            Id = cc.Contact_ID,
                                            FirstName = cc.FirstName,
                                            LastName = cc.LastName,
                                            ContactNumber = cc.Mobile,
                                            Email = cc.Email
                                        }).ToList();

                                var list2 = list.Where(p => !model.searchList.Any(p2 => p2.Id == p.Id));

                                model.searchList.AddRange(list2);
                            }

                            // Search for emails only
                        }
                        else if (query.Contains("@") && !query.Contains(" "))
                        {
                            var list = (from cc in context.Common_Contact
                                        where (cc.Email == query || cc.Email2 == query)
                                        select new ContactDetails
                                        {
                                            Id = cc.Contact_ID,
                                            FirstName = cc.FirstName,
                                            LastName = cc.LastName,
                                            ContactNumber = cc.Mobile,
                                            Email = cc.Email
                                        }).ToList();


                            model.searchList.AddRange(list);

                            // Search for single names
                        }
                        else if (!query.Contains(" "))
                        {
                            var list = (from cc in context.Common_Contact
                                        where (cc.FirstName == query || cc.LastName == query)
                                        select new ContactDetails
                                        {
                                            Id = cc.Contact_ID,
                                            FirstName = cc.FirstName,
                                            LastName = cc.LastName,
                                            ContactNumber = cc.Mobile,
                                            Email = cc.Email
                                        }).ToList();

                            model.searchList.AddRange(list);
                        }

                        return View("Registrations", model);
                    }
                }
                catch (Exception e)
                {
                    throw e;
                }
            }
            else
            {
                return View("Error", "Shared");
            }
        }

        [HttpPost]
        public ActionResult Register(PurchaseViewModel model)
        {
            using (PlanetshakersEntities context = new PlanetshakersEntities())
            {
                if (model.selectedEvent == 0)
                {
                    model.selectedEvent = (from ec in context.Events_Conference
                                           where ec.SortOrder > 0
                                           orderby ec.SortOrder
                                           select ec.Conference_ID).FirstOrDefault();
                }

                if (model.selectedPaymentType > 0)
                {
                    SelfAllocateModel selfallocatedmodel = new SelfAllocateModel();

                    if (model.Comments == null)
                    {
                        model.Comments = String.Empty;
                    }

                    model.RegoTypes = new Dictionary<int, int>();

                    // TODO: FIX THIS!! Data should come from View and require no re-creation
                    // Recreate the model because input from view is not coming through
                    for (int i = 0; i < model.rego_type_list.Count; i++)
                    {
                        model.RegoTypes.Add(model.rego_type_list[i].RegistrationType_ID, model.qty[i]);
                    }

                    // Create cart models
                    var cartModel = new CartModel(model.selectedEvent);

                    cartModel.ContactId = model.selectedID;
                    cartModel.Comments = model.Comments;
                    Session["Cart"] = cartModel;

                    // Populate cart model
                    var regotypes = model.RegoTypes.Where(x => x.Value > 0).ToList();
                    foreach (var pair in regotypes)
                    {
                        cartModel.Cart.Add(new CartItem
                        {
                            ContactId = model.selectedID,
                            reg_id = pair.Key,
                            reg_name = (from ert in context.Events_RegistrationType
                                        where ert.RegistrationType_ID == pair.Key
                                        select ert.RegistrationType).FirstOrDefault(),
                            event_id = cartModel.Event.id,
                            event_name = (from ec in context.Events_Conference
                                          where ec.Conference_ID == cartModel.Event.id
                                          select ec.ConferenceName).FirstOrDefault(),
                            single_price = model.rego_type_list.Where(x => x.RegistrationType_ID == pair.Key).First().RegistrationCost,
                            currency = (from ec in context.Events_Conference
                                        where ec.Conference_ID == model.selectedEvent
                                        join ba in context.Common_BankAccount on ec.BankAccount_ID equals ba.BankAccount_ID
                                        select ba.Currency).FirstOrDefault(),
                            quantity = pair.Value
                        });
                    }

                    if (cartModel.Voucher != null)
                    {
                        var v = cartModel.Voucher.value;
                        var s = cartModel.Cart.Sum(i => i.subtotal);

                        cartModel.Voucher.applied_value = s < v ? s : v;
                    }

                    if (model.selectedPaymentType == 3)
                        return RedirectToAction("Summary", "Payment");

                    // Stripe CC bypass for admin use only
                    if (model.selectedPaymentType == 10000)
                    {
                        model.selectedPaymentType = 3;
                    }

                    if (cartModel.CCPayment == null)
                    {

Mobile/Views/Administration/AllocateQuickAddTicket.cshtml
@model Planetshakers.Events.Models.SelfAllocateModel
@{
    /**/

    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">

        <div class="col-lg-12 border-bottom">
            <div>
                <h3>Conference Registration</h3>
            </div>
        </div>
</div>


    <div class="row my-3">
        <div class="col-lg-7">
            <h4>Do you want to allocate to this person?</h4>
        </div>
        <div class="col-lg-5" style="padding-top: 15px;">
            <input type="checkbox" id="selfAllocateChose" />
        </div>
    </div>

    @using (Html.BeginForm("SelfAllocate", "Administration", FormMethod.Post, new { }))
    {
        <div id="selfAllcoteSection" style="display: none;" class="row my-3">
            <div class="col-lg-12" id="registrationTypeSelect">
                <label>Select Registration Type: <span class="redstar" style="color: red">*</span></label><br /><br />
                @Html.DropDownListFor(m => m.RegistrationType_ID, Model.AvailableRegistrationTypeList, "Select Registration Type", new { @id = "selfAllocateRegoType", required = "required", @class="form-control" })
            </div>
            <br />
            <div id="selfAllocatedAttended" class="col-lg-12" style="display: none;">
                <br />
                <label>Attended?  </label><span>@Html.CheckBoxFor(m => m.Attended, new { })</span>
                <br /><br />
            </div>
            <br />
            @Html.HiddenFor(m => m.Conference_ID)
            @Html.HiddenFor(m => m.Venue_ID)
            @Html.HiddenFor(m => m.Contact_ID)

            <div class="col-lg-10"></div>
            <div class="col-lg-2 my-2">
                <button class="btn btn-primary btn-block" type="submit">Allocate</button>
            </div>
            <br />
        </div>

    }
    <div class="row my-3">
        <div class="col-lg-10"></div>
        <div class="col-lg-2">
            <button onclick="window.location.href = '@Url.Action("RegistrationSuccess", "Administration")'" id="continueRegistrationSuccess" class="btn btn-primary btn-block">Continue</button>
        </div>
    </div>


    
    

Mobile/Views/Administration/Allocations.cshtml
@model Planetshakers.Events.Models.AllocationViewModel
@{
                /**/

                Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">

    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Conference Allocation</h3>
        </div>
    </div>
</div>

<div>
    @using (Html.BeginForm("SearchContactAllocation", "Administration", FormMethod.Post, new { @class="form-group row mx-3" }))
    {
        <div class="col-lg-9">
            @Html.TextBox("query", "", new { @placeholder = "Name or Email", @class="form-control" })
        </div>
        <div class="col-lg-3">
            <input type="submit" value="Search" class="btn btn-primary btn-block" />
        </div>
    }
</div>

<div>
    <div class="row mx-3 form-group">
        @if (Model.searchList != null)
        {
            <div class="col-lg-12">
                <table style="width:100%" class="table table-bordered">
                    <tr class="table-active">
                        <th>Full Name</th>
                        <th>Mobile</th>
                        <th>Email</th>
                        <th></th>
                    </tr>
                    @foreach (var c in Model.searchList)
                    {
                        <tr>
                            @using (Html.BeginForm("Allocate", "Administration", FormMethod.Post))
                            {
                                <td>@c.FirstName @c.LastName</td>
                                <td>@c.ContactNumber</td>
                                <td>@c.Email</td>
                                @Html.HiddenFor(m => m.Contact_ID, new { Value = c.Id })
                                <td><input type="submit" value="Select" class="btn btn-primary btn-block" /></td>
                            }
                        </tr>
                    }
                </table>
            </div>
        }
        else
        {
            <div class="col-lg-12">
                <p><strong>No results found.</strong></p>
            </div>
        }
    </div>
    
</div>

<div>
    @if (Model.Contact_ID > 0)
    {
        using (Html.BeginForm("Allocate", "Administration", FormMethod.Post, new { @class = "form-group row mx-3" }))
        {
            <div class="col-lg-12">
                @Html.DropDownListFor(m => m.Venue_ID, Model.EventList, "Select Trip", new { @class= "form-control" })
            </div>
            if (Model.Venue_ID > 0)
            {
                <div class="col-lg-12">
                    <br />
                    <table style="width:100%" class="table table-bordered">
                        <thead class="table-active">
                            <tr>
                                <th>Registration Type</th>
                                <th>Allocated</th>
                                <th>Unallocated</th>
                            </tr>
                        </thead>

                        <tbody id="unallocatedRegistrationType">
                            @foreach (var r in Model.unallocatedRegoList)
                            {
                                <tr>
                                    <td>@r.RegistrationType</td>
                                    <td>@r.Allocated</td>
                                    <td>@r.Unallocated</td>
                                </tr>
                            }
                        </tbody>

                    </table>
                    <br />

                    <table style="width:100%" class="table table-bordered">
                        <thead class="table-active">
                            <tr>
                                <th>Registration ID</th>
                                <th>Name</th>
                                <th>Mobile</th>
                                <th>Email</th>
                            </tr>
                        </thead>

                        <tbody id="allocatedRegistration">
                            @foreach (var r in Model.AllocatedRegoList)
                            {
                                <tr>
                                    <td>@r.ID</td>
                                    <td>@r.FirstName @r.LastName</td>
                                    <td>@r.Mobile</td>
                                    <td>@r.Email</td>
                                </tr>
                            }
                        </tbody>

                    </table>
                    <br />
                </div>

                <div class="col-lg-6" id="registrationTypeSelect">
                    @Html.DropDownListFor(m => m.RegistrationType_ID, Model.AvailableRegistrationTypeList, "Select Registration Type", new { @class="form-control" })
                    <br />
                </div>
                <div class="col-lg-6">
                    @Html.DropDownListFor(m => m.SelectedOption, Model.AllocateOption, "Select Option", new { @class = "form-control" })
                    <br />
                </div>
            }
            <br />
            <div class="col-lg-12">
                @Html.HiddenFor(m => m.Contact_ID, new { Value = Model.Contact_ID })
                <input type="submit" value="Submit" class="btn btn-primary btn-block" />
            </div>

        }
    }
</div>

Mobile/Views/Administration/ConferenceCallList.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

Mobile/Views/Administration/Register.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<div class="row">

    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Registration Admin Panel</h3>
        </div>
    </div>

</div>
<div>
    @using (Html.BeginForm("SearchContact", "Administration", FormMethod.Post, new { @class="row mx-3 form-group" }))
    {
        <div class="col-lg-9">
            @Html.TextBox("query", new { @class = "form-control" })
        </div>
        <div class="col-lg-3">
            <input type="submit" value="Search" class="btn btn-primary btn-block" />
        </div>
    }
</div>

<div>
    <div class="row">
        @if (Model.searchList != null)
        {
            <div class="col-lg-12">
                <table style="width:100%" class="table table-bordered">
                    <tr class="table-active">
                        <th>Full Name</th>
                        <th>Mobile</th>
                        <th>Email</th>
                        <th></th>
                    </tr>
                    @foreach (var c in Model.searchList)
                    {
                        <tr>
                            @using (Html.BeginForm("Register", "Administration"))
                            {
                                <td>@c.FirstName @c.LastName</td>
                                <td>@c.Mobile</td>
                                <td>@c.Email</td>
                                @Html.Hidden("selectedContact", new { Value = c.Contact_ID })
                                <td><input type="submit" class="btn btn-primary btn-block" /></td>
                            }
                        </tr>
                    }
                </table>
            </div>
        }
        else
        {
            <div class="col-lg-12">
                <p><strong>No results found.</strong></p>
            </div>
        }

    </div>
</div>

Mobile/Views/Administration/RegisterNew.cshtml
@model Planetshakers.Events.Models.PurchaseViewModel
@{
    ViewBag.Title = "RegisterNew";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">
    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Conference Registration | New</h3>
        </div>
    </div>
</div>
    
<div>
    @using (Html.BeginForm("SubmitNew", "Administration", FormMethod.Post, new { @class="row mx-3 form-group" }))
    {
        <div class="col-lg-12">
            @Html.LabelFor(m => m.NewFirstName) @Html.TextBoxFor(m => m.NewFirstName, new { required = "required", @class = "form-control" })<br />
            @Html.LabelFor(m => m.NewLastName) @Html.TextBoxFor(m => m.NewLastName, new { required = "required", @class = "form-control" })<br />
            @Html.LabelFor(m => m.NewGender) @Html.DropDownListFor(m => m.NewGender, Model.GenderList, "", new { @class = "form-control" })<br />
            @Html.LabelFor(m => m.NewMobile) @Html.TextBoxFor(m => m.NewMobile, new { @class = "form-control" })<br />
            @Html.LabelFor(m => m.NewEmail) @Html.TextBoxFor(m => m.NewEmail, new { @class = "form-control" })<br />
            <input type="submit" value="submit" class="btn btn-primary btn-block" />
        </div>

    }
</div>
   

Mobile/Views/Administration/RegistrationAdminIndex.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">

    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Registration Administration</h3>
        </div>
    </div>
</div>

<div>
    <div class="row mx-3 form-group" >
        <div class="col-lg-6">
            <a href="@Url.Action("Allocations","Administration")" class="btn btn-large btn-primary btn-block py-4 my-2 my-lg-0" style="font-size: 2rem;">Allocation</a>
        </div>
        <div class="col-lg-6">
            <a href="@Url.Action("Registrations","Administration")" class="btn btn-large btn-primary btn-block py-4 my-2 my-lg-0" style="font-size: 2rem;">Registration</a>
        </div>
    </div>
</div>
        

Mobile/Views/Administration/SponsorshipConfirmation.cshtml
@{
    /**/

    ViewBag.Title = "Sponsorship Confirmation";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";

}
<div class="container-fluid">

    <div class="card shadow h-100 py-2 my-5">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12">
                    <div class="row mx-0 px-2">
                        <div class="col-lg-12 border-bottom">
                            <h3>@ViewBag.Title</h3>
                        </div>
                    </div>
                    <div class="mx-0 px-2">
                        <div class="col-lg-12">
                            <h5>Thank you for Sponsoring for @ViewBag.EventName! Your generosity is appreciated.</h5>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">

                </div>
                <div class="col-3">
                    <button class="btn btn-primary btn-block" onclick="window.location.href = '@Url.Action("SponsorshipPayment", "Administration")'">New Sponsorship Payment</button>
                </div>
                <div class="col-3">
                    <button class="btn btn-primary btn-block" onclick="window.location.href = '@Url.Action("SponsorshipIndex", "Administration")'">Sponsorship Management</button>
                </div>
            </div>
        </div>
    </div>

</div>