Mobile/Controllers/ManagementController.cs
using Planetshakers.Core.DataInterfaces;
using Planetshakers.Core.Models;
using Planetshakers.Events.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Planetshakers.Events.Controllers
{
    [Authorize]
    public class ManagementController : Controller
    {

        private readonly IManagementRepository _repository;

        public ManagementController(IManagementRepository repository)
        {
            _repository = repository;
        }
        public ActionResult DatabaseRoleManagement()
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            return View("DatabaseRoleManagement", model);
        }

        [HttpPost]
        public ActionResult SaveDbRolePermission(int DbRolePermissionID, string DbObjectName, string DbObjectDesc, bool DbRolePermRead, bool DbRolePermWrite)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.SaveDbRolePermission(DbRolePermissionID, DbObjectName, DbObjectDesc, DbRolePermRead, DbRolePermWrite);
            return Json(new { success });
        }

        [HttpPost]
        public ActionResult DeleteDbRole(int DbRoleID)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.DeleteDbRole(DbRoleID);
            return Json(new { success });
        }

        public ActionResult AddDbRolePage()
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            return View("AddDatabaseRole", model);
        }

        
        [HttpPost]
        public ActionResult AddDbRole(string DbRoleName)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.AddDbRole(DbRoleName);
            return Json(new {success });
        }

        [HttpPost]
        public ActionResult SaveNewDbRolePermission(int DbObjID, bool DbRolePermRead, bool DbRolePermWrite)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.SaveNewDbRolePermission(DbObjID, DbRolePermRead, DbRolePermWrite);
            return Json(new { success });
        }


        public ActionResult AccessLevel()
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            model.GenerateResult = false;
            return View("AccessLevel", model);
        }

        public ActionResult GenerateAccessLevelPermissionSearchResult(DatabaseRoleManagementModel model)
        {
            model.GenerateResult = true;
            return View("AccessLevel", model);
        }

        public ActionResult GenerateContactAccessLevelPermission(DatabaseRoleManagementModel model)
        {
            model.GenerateResult = true;
            model.userDbPermDictionary = new Dictionary<int, List<AccessLevelPermission>>();
            model.userDbRoleDictionary = new Dictionary<int, List<ContactAccessLevel>>();
            foreach (var user in model.searchedResultContactList)
            {
                List<AccessLevelPermission> userdbroleperm = new List<AccessLevelPermission>();
                List<ContactAccessLevel> userRole = new List<ContactAccessLevel>();
                userdbroleperm = _repository.GetContactAccessLevelPermission(user.Contact_ID);
                model.userDbPermDictionary.Add(user.Contact_ID, userdbroleperm);
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    userRole = (from cdr in context.Common_ContactDatabaseRole
                                join dbr in context.Common_DatabaseRole
                                on cdr.DatabaseRole_ID equals dbr.DatabaseRole_ID
                                where cdr.Contact_ID == user.Contact_ID && dbr.Module == "Believe"
                                select new ContactAccessLevel
                                {
                                    ContactId = user.Contact_ID,
                                    DbRoleId = cdr.DatabaseRole_ID,
                                    Name = dbr.Name,
                                    Module = dbr.Module,
                                    DateAdded = cdr.DateAdded
                                }).ToList();
                    model.userDbRoleDictionary.Add(user.Contact_ID, userRole);
                }
            }
            return View("AccessLevel", model);
        }

        public ActionResult DeleteContactAccessLevel(int DbRoleID, int ContactID)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.DeleteContactAccessLevel(DbRoleID, ContactID);
            return Json(new { success });
        }

        public ActionResult AddContactAccessLevel(int DbRoleID, int ContactID)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.AddContactAccessLevel(DbRoleID, ContactID);
            using (PlanetshakersEntities context = new PlanetshakersEntities())
            {
                var dbRole = (from cdr in context.Common_ContactDatabaseRole
                              join dr in context.Common_DatabaseRole
                              on cdr.DatabaseRole_ID equals dr.DatabaseRole_ID
                              where cdr.Contact_ID == ContactID && cdr.DatabaseRole_ID == DbRoleID
                              select dr).FirstOrDefault();
                return Json(new { success, dbRoleID = DbRoleID, contactID = ContactID, addedDate = DateTime.Now.ToString(), dbRoleName = dbRole.Name });
            } 
            
        }

        public ActionResult UpdateAccessLevelReadPermission(int DbObjID, int ContactID, bool Read)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.UpdateAccessLevelReadPermission( DbObjID,  ContactID,  Read);
            return Json(new { success });
        }

        public ActionResult UpdateAccessLevelWritePermission(int DbObjID, int ContactID, bool Write)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.UpdateAccessLevelWritePermission(DbObjID, ContactID, Write);
            return Json(new { success });
        }

        public ActionResult AddContactAccessLevelReadWritePermission(int DbObjID, int ContactID, bool ReadCheck, bool WriteCheck)
        {
            DatabaseRoleManagementModel model = new DatabaseRoleManagementModel();
            bool success = model.AddContactAccessLevelReadWritePermission(DbObjID, ContactID, ReadCheck, WriteCheck);
            return Json(new { success });
        }
    }
}

Mobile/Views/Shared/ErrorDetails.cshtml
@{
    ViewBag.Title = "ErrorDetails";
}


<h2>An error just occured.</h2>

<p>
    Currently unable to log you in at this point. 
</p>

<p>
    Message: @(((HandleErrorInfo)ViewData.Model).Exception.Message)
</p>

Mobile/Views/Shared/Footer.cshtml
<footer id="navbar">
</footer>

<footer id="navbar-memberList">
    <a href="javascript:app.toggleList('.attendance-list', 0);" class="icon-custom new-people">New</a>
    <a href="javascript:app.toggleList('.attendance-list', 1);" class="icon-custom partner">Partner</a>
    <a href="javascript:app.toggleList('.attendance-list', 2);" class="icon-custom contact">Contact</a>
</footer>

<footer id="navbar-memberDetails">
    <a href="javascript:app.toggleList('.member-details', 0);" class="icon user">Profile</a>
    <a href="javascript:app.toggleList('.member-details', 1);" class="icon message">Comments</a>
</footer>

Mobile/Views/Shared/SideBar.cshtml
<!-- Nav Item - Pages Collapse Menu -->
@{
    var Contact_ID = CurrentContext.Instance.User.ContactID;
    var accessList = Planetshakers.Events.Controllers.AdministrationController.HasObjectAccess(Contact_ID);

}
@if (Request.IsAuthenticated)
{
    //if (Planetshakers.Events.Controllers.AdministrationController.HasAdminAccess(Contact_ID))
    //{
    // Trip Setup Tab
    if (accessList.Contains(37) || accessList.Contains(38))
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseConference" aria-expanded="true" aria-controls="collapseConference">
                <i class="fas fa-fw fa-folder"></i>
                <span>Trip</span>
            </a>
            <div id="collapseConference" class="collapse" aria-labelledby="headingConference" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Event:</h6>
                    @if (accessList.Contains(37))
                    {
                        <a class="collapse-item" href="@Url.Action("Conference","Setup")">Set Up</a>
                        <a class="collapse-item" href="@Url.Action("SortConference","Setup")">Sort Order</a>
                        <a class="collapse-item" href="@Url.Action("SignUpLinks","Setup")">SignUp Links</a>
                    }
                    @if (accessList.Contains(38))
                    {
                        <a class="collapse-item" href="@Url.Action("RegistrationType","Setup")">Registration Types</a>
                        <a class="collapse-item" href="@Url.Action("TermsAndConditions","Setup")">Terms and Conditions</a>
                    }
                </div>
            </div>
        </li>
    }

    // Application Setup Tab
    if (accessList.Contains(39) || accessList.Contains(40))
    {
        <li class="nav-item">

            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseApplication" aria-expanded="true" aria-controls="collapseApplication">
                <i class="fas fa-fw fa-folder"></i>
                <span>Application</span>
            </a>
            <div id="collapseApplication" class="collapse" aria-labelledby="headingApplication" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Application:</h6>
                    @if (accessList.Contains(40))
                    {
                        <a class="collapse-item" href="@Url.Action("Application","Application")">Application</a>
                    }
                    @if (accessList.Contains(39))
                    {
                        <a class="collapse-item" href="@Url.Action("Questions","Application")">Questions</a>
                        <a class="collapse-item" href="@Url.Action("DocumentType","Application")">Document Types</a>
                    }
                </div>
            </div>

        </li>
    }
    //add accessibility - for contact profile and also sponsorship
    if (accessList.Contains(41) || accessList.Contains(58))
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseRegistration" aria-expanded="true" aria-controls="collapseRegistration">
                <i class="fas fa-fw fa-folder"></i>
                <span>Registration</span>
            </a>

            <div id="collapseRegistration" class="collapse" aria-labelledby="headingRegistration" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Registration:</h6>
                    @if (accessList.Contains(41))
                    {
                        <a class="collapse-item" href="@Url.Action("EventSearch","Registration")">Registration</a>
                    }
                    @if (accessList.Contains(58))
                    {
                        <a class="collapse-item" href="@Url.Action("SponsorshipIndex", "Administration")">Sponsorship</a>
                    }
                </div>
            </div>
        </li>
    }
    @*Team Management*@
    if (accessList.Contains(42) || accessList.Contains(43))
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseTeams" aria-expanded="true" aria-controls="collapseTeams">
                <i class="fas fa-fw fa-folder"></i>
                <span>Teams</span>
            </a>
            <div id="collapseTeams" class="collapse" aria-labelledby="headingTeams" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Teams:</h6>
                    @if (accessList.Contains(42))
                    {
                        <a class="collapse-item" href="@Url.Action("Teams","Teams")">Teams</a>
                    }
                    @if (accessList.Contains(43))
                    {
                        <a class="collapse-item" href="@Url.Action("TeamRole","Teams")">Team Role</a>
                    }
                </div>
            </div>
        </li>
    }
    @*Host Events*@
    if (accessList.Contains(44) || accessList.Contains(45))
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseHostEvents" aria-expanded="true" aria-controls="collapseHostEvents">
                <i class="fas fa-fw fa-folder"></i>
                <span>Host Events</span>
            </a>
            <div id="collapseHostEvents" class="collapse" aria-labelledby="headingTeams" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Host Events:</h6>
                    @if (accessList.Contains(45))
                    {
                        <a class="collapse-item" href="@Url.Action("HostEvents","HostEvents")">Attendance</a>
                    }
                    @if (accessList.Contains(44))
                    {
                        <a class="collapse-item" href="@Url.Action("HostEventManagement","HostEvents")">Management</a>
                    }
                </div>
            </div>
        </li>
    }
    @*Email and SMS mailing list*@
    if (accessList.Contains(47) || accessList.Contains(46))
    {
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseAdministration" aria-expanded="true" aria-controls="collapseAdministration">
                <i class="fas fa-fw fa-folder"></i>
                <span>Administration</span>
            </a>
            <div id="collapseAdministration" class="collapse" aria-labelledby="headingAdministration" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Mailing list:</h6>
                    @if (accessList.Contains(46))
                    {
                        <a class="collapse-item" href="@Url.Action("EmailMailingList", "Administration")">Email</a>
                    }
                    @if (accessList.Contains(47))
                    {
                        <a class="collapse-item" href="@Url.Action("SmsMailingList", "Administration")">SMS</a>
                    }
                </div>
            </div>
        </li>
    }

    if (accessList.Contains(48) || accessList.Contains(49))
    {
        //Management Tabs
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseManagement" aria-expanded="true" aria-controls="collapseManagement">
                <i class="fas fa-fw fa-folder"></i>
                <span>Management</span>
            </a>
            <div id="collapseManagement" class="collapse" aria-labelledby="headingManagement" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Management:</h6>
                    @if (accessList.Contains(48))
                    {
                        <a class="collapse-item" href="@Url.Action("DatabaseRoleManagement","Management")">Database Role</a>
                    }
                    @if (accessList.Contains(49))
                    {
                        <a class="collapse-item" href="@Url.Action("AccessLevel","Management")">Access Level</a>
                    }
                </div>
            </div>
        </li>
    }

    if (accessList.Contains(50) || accessList.Contains(51) || accessList.Contains(52) || accessList.Contains(53) || accessList.Contains(54)
        || accessList.Contains(59) || accessList.Contains(60))
    {
        //Reporting Tabs
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseReport" aria-expanded="true" aria-controls="collapseReport">
                <i class="fas fa-fw fa-folder"></i>
                <span>Report</span>
            </a>
            <div id="collapseReport" class="collapse" aria-labelledby="headingReport" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Report:</h6>
                    @if (accessList.Contains(59))
                    {
                        <a class="collapse-item" href="@Url.Action("ApplicationReport", "Report")">Application Report</a>
                    }
                    @if (accessList.Contains(60))
                    {
                        <a class="collapse-item" href="@Url.Action("DocumentReport", "Report")">Document Reports</a>
                    }
                    @if (accessList.Contains(50))
                    {
                        <a class="collapse-item" href="@Url.Action("SummaryReport","Report")">Summary Reports</a>
                    }
                    @if (accessList.Contains(51))
                    {
                        <a class="collapse-item" href="@Url.Action("RegistrationReport","Report")">Registration Type Report</a>
                    }
                    @if (accessList.Contains(52))
                    {
                        <a class="collapse-item" href="@Url.Action("TotalRegistrantsReport","Report")">Quick Total Report</a>
                    }
                    @if (accessList.Contains(53))
                    {
                        <a class="collapse-item" href="@Url.Action("TotalRegistrationReport","Report")">Breakdown Report</a>
                    }
                    @if (accessList.Contains(54))
                    {
                        <a class="collapse-item" href="@Url.Action("CheckInReport","Report")">Check In Report</a>
                    }
                </div>
            </div>
        </li>
    }


    if (accessList.Contains(55) || accessList.Contains(56) || accessList.Contains(57) || accessList.Contains(61))
    {
        //Finance Reporting Tabs
        <li class="nav-item">
            <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseFinanceReport" aria-expanded="true" aria-controls="collapseReport">
                <i class="fas fa-fw fa-folder"></i>
                <span>Finance Report</span>
            </a>
            <div id="collapseFinanceReport" class="collapse" aria-labelledby="headingReport" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <h6 class="collapse-header">Report:</h6>
                    @if (accessList.Contains(55))
                    {
                        <a class="collapse-item" href="@Url.Action("BankingReport","Report")">Banking Reports</a>
                        @*<a class="collapse-item" href="@Url.Action("PaymentReport","Report")">Payment Reports</a>*@
                    }
                    @if (accessList.Contains(61))
                    {
                        <a class="collapse-item" href="@Url.Action("PaymentSummary","Report")">Payment Summary</a>
                    }
                    @if (accessList.Contains(56))
                    {
                        <a class="collapse-item" href="@Url.Action("AuditReport","Report")">Audit Reports</a>
                    }
                    @if (accessList.Contains(57))
                    {
                        <a class="collapse-item" href="@Url.Action("PurchaseReport","Report")">Purchase Reports</a>
                    }
                </div>
            </div>
        </li>
    }
    //}
}

Mobile/Views/Shared/_Layout.cshtml
@using Planetshakers.Events.Models
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="robots" content="noindex, nofollow" />
    <meta name="google-signin-client_id" content="461269663134-11hc88njamvmk57f9htifpfc0bt5hsqo.apps.googleusercontent.com">


    <title>@BaseModel.pageTitle</title>

    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/icons.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/font-awesome-4.4.0/css/font-awesome.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap/css/bootstrap.dataTable.min.css")">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap/sb-admin-2.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap/css/bootstrap.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap/css/bootstrap-select.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap/css/bootstrap.multiselect.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/bootstrap/vendor/fontawesome-free/css/all.css")">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/footable/css/footable.core.min.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/planetshakers.css")" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/app.css?v=" + @GlobalText.Version)" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/jquery-ui.css")" />






    @*<link rel="stylesheet" media="only screen and (max-device-width: 480px)" href="@Url.Content("~/Content/app.phone.css")">
        <link rel="stylesheet" media="only screen and (device-width: 768px)" href="@Url.Content("~/Content/app.tablet.css")">*@

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="@Url.Content("~/Content/ico/apple-touch-icon-144-precomposed.png")" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="@Url.Content("~/Content/ico/apple-touch-icon-114-precomposed.png")" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="@Url.Content("~/Content/ico/apple-touch-icon-72-precomposed.png")" />
    <link rel="apple-touch-icon-precomposed" href="@Url.Content("~/Content/ico/apple-touch-icon-57-precomposed.png")" />
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/jquery/jquery.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui.js")"></script>

    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    @*<script type="text/javascript" src="@Url.Content("~/Scripts/jqmobi/v1.2rc2/jq.mobi.min.js")"></script>*@

    <!-- include touch.js on desktop browsers only -->

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-33278290-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'https://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body>

    @RenderBody()
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/umd/Popper.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/js/bootstrap-select.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/sb-admin-2.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/jquery.dataTables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/dataTables.buttons.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/jszip.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/buttons.flash.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/pdfmake.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/vfs_fonts.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/buttons.html5.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/dataTables.bootstrap4.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/dataTables.responsive.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/vendor/datatables/dataTables.date-euro.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jszip.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/dataTables.buttons.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/buttons.html5.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/footable/js/footable.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.setup.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.management.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.transfer.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.report.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.administration.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.multi-select.min.js")"></script>

    <!--https://code.jquery.com/jquery-3.5.1.js-->
    <script type="text/javascript" src="@Url.Content("~/Scripts/json2.js")"></script>
    <script type="text/javascript" charset="utf-8" src="@Url.Content("~/Scripts/app.MemberComment.js?v=" + @GlobalText.Version)"></script>
    <script type="text/javascript" charset="utf-8" src="@Url.Content("~/Scripts/app.ReportSubmission.js?v=" + @GlobalText.Version)"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/app.Attendance.js?v=" + @GlobalText.Version)"></script>
    <script type="text/javascript" charset="utf-8" src="@Url.Content("~/Scripts/app.js?v=" + @GlobalText.Version)"></script>

    <!--for multiselect-->
    <link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>

    @RenderSection("scripts", false)
</body>
</html>

Mobile/Views/Shared/_LayoutFullScreen.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<div id="jQUi">

    <div id="content" class="full-screen">
        @RenderBody()
    </div>

</div>*@

<div id="body">
    <section class="content-wrapper main-content clear-fix">
        @RenderBody()
    </section>
</div>

@*<script type="text/javascript">
    $.ui.ready(function () {
        $.ui.toggleHeaderMenu(false); //force hide
        $.ui.removeFooterMenu();
    });
</script>*@

Mobile/Views/Shared/_Management.cshtml
@if (CurrentContext.Instance.HasManagementAccess())
{
    <li class="">
        <a href="@(Url.Action("Index", "Management"))">Management</a>
    </li>
}

Mobile/Views/Shared/_NoLayout.cshtml
 @RenderBody()