Mobile/Controllers/CheckInController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.SessionState;
using System.Collections.Generic;
using System.Diagnostics;
using System.Data.SqlClient;
using Planetshakers.Core.DataInterfaces;
using Planetshakers.Events.Security;
using Planetshakers.Events.Models;
using Planetshakers.Core.Models;

namespace Planetshakers.Events.Controllers
{
    [Authorize]
    public class CheckInController : Controller
    {
        private readonly ICheckInRepository _repository;

        public CheckInController(ICheckInRepository repository)
        {
            _repository = repository;
        }

        #region Conference

        public ActionResult Conference()
        {
            if (HasRegoAccess(CurrentContext.Instance.User.ContactID))
            {
                string category = "Checkin: Conference Click";
                string criteria = "Contact ID: " + CurrentContext.Instance.User.ContactID.ToString();

                //Log to Common_Accesslog table
                Business.MWebMain.LogAction(ref category, ref criteria, CurrentContext.Instance.User.ContactID.ToString());

                return View();
            }
            else
            {
                ViewBag.Message = "You do not have access to this page.";
                return View("Error");
            }
        }

        public ActionResult Submit(List<int> attended)
        {
            string category = "Page Load";
            string criteria = "Contact ID: " + CurrentContext.Instance.User.ContactID.ToString();

            //Log to Common_Accesslog table
            Business.MWebMain.LogAction(ref category, ref criteria, CurrentContext.Instance.User.ContactID.ToString());

            try
            {
                if (attended == null)
                {
                    ViewBag.Message = "No ID(s) seleceted";
                    return View("Error");
                }

                foreach (int regos in attended)
                {
                    _repository.MarkById(regos);
                }

                ViewBag.Attended = attended;

                return View("Success");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View("Error");
            }
            
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Attended()
        {
            return View();
        }

        public ActionResult NotInRange()
        {
            return View();
        }

        #region Group Registrations
        public ActionResult GroupRegistrations()
        {
            if (HasRegoAccess(CurrentContext.Instance.User.ContactID))
            {
                string category = "Page Load";
                string criteria = "Contact ID: " + CurrentContext.Instance.User.ContactID.ToString();

                //Log to Common_Accesslog table
                Business.MWebMain.LogAction(ref category, ref criteria, CurrentContext.Instance.User.ContactID.ToString());

                var model = new RegistrationViewModel();

                return View(model);
            }
            else
            {
                ViewBag.Message = "You do not have access to this page.";
                return View("Error");
            }
        }

        #endregion

        #region Search
        public ActionResult Registrations()
        {
            if (HasRegoAccess(CurrentContext.Instance.User.ContactID))
            {
                string category = "Page Load";
                string criteria = "Contact ID: " + CurrentContext.Instance.User.ContactID.ToString();

                //Log to Common_Accesslog table
                Business.MWebMain.LogAction(ref category, ref criteria, CurrentContext.Instance.User.ContactID.ToString());

                var model = new RegistrationViewModel();

                return View(model);
            }
            else
            {
                return RedirectToAction("Error", "Index");
            }

        }

        [HttpPost]
        public ActionResult SearchRegistration(string query)
        {

            if (query != null)
            {
                int i;

                // Don't search for short queries
                if (query.Length < 3)
                {
                    ViewBag.Message = "Query is too short. Please provide the full name or full email.";
                    return View("Error");
                }

                if (int.TryParse(query, out i)){
                    ViewBag.Message = "Invalid query. Please search by full name or full email.";
                    return View("Error");
                }

                try
                {
                    //using (PlanetshakersEntities context = new PlanetshakersEntities())
                    //{
                        var model = new RegistrationViewModel();
                    //    model.searchList = new List<Registration>();

                    //    // Search for names with spaces
                    //    if (query.Contains(" "))
                    //    {
                    //        var parts = query.ToLower().Split();

                    //        var list = (from er in context.vw_Events_RegistrationCheckIn
                    //                    join cc in context.Common_Contact
                    //                        on er.Contact_ID equals cc.Contact_ID
                    //                    where (er.FirstName + " " + er.LastName == query || er.LastName + " " + er.FirstName == query)
                    //                    select new Registration
                    //                    {
                    //                        ID = er.Registration_ID,
                    //                        FirstName = er.FirstName,
                    //                        LastName = er.LastName,
                    //                        Conference_ID = er.Conference_ID,
                    //                        ConferenceName = er.ConferenceName,
                    //                        Email = (String.IsNullOrEmpty(cc.Email) ? cc.Email2 : cc.Email)
                    //                    }).ToList();

                    //        model.searchList.AddRange(list);

                    //        foreach (var s in parts)
                    //        {
                    //            list = (from er in context.vw_Events_RegistrationCheckIn
                    //                    join cc in context.Common_Contact
                    //                        on er.Contact_ID equals cc.Contact_ID
                    //                    where (er.FirstName.StartsWith(s) || er.LastName.StartsWith(s))
                    //                    select new Registration
                    //                    {
                    //                        ID = er.Registration_ID,
                    //                        FirstName = cc.FirstName,
                    //                        LastName = cc.LastName,
                    //                        Conference_ID = er.Conference_ID,
                    //                        ConferenceName = er.ConferenceName,
                    //                        Email = (String.IsNullOrEmpty(cc.Email) ? cc.Email2 : cc.Email)
                    //                    }).ToList();

                    //            var list2 = list.Where(p => !model.searchList.Any(p2 => p2.ID == p.ID));

                    //            model.searchList.AddRange(list2);
                    //        }

                    //        // Search for emails only
                    //    } else if (query.Contains("@") && !query.Contains(" "))
                    //    {
                    //        var list = (from er in context.vw_Events_RegistrationCheckIn
                    //                    join cc in context.Common_Contact
                    //                        on er.Contact_ID equals cc.Contact_ID
                    //                    where (cc.Email == query || cc.Email2 == query)
                    //                    select new Registration
                    //                    {
                    //                        ID = er.Registration_ID,
                    //                        FirstName = cc.FirstName,
                    //                        LastName = cc.LastName,
                    //                        Conference_ID = er.Conference_ID,
                    //                        ConferenceName = er.ConferenceName,
                    //                        Email = (String.IsNullOrEmpty(cc.Email) ? cc.Email2 : cc.Email)
                    //                    }).ToList();

                    //        model.searchList.AddRange(list);
                        
                    //    // Search for single names
                    //    } else if (!query.Contains(" "))
                    //    {
                    //        var list = (from er in context.vw_Events_RegistrationCheckIn
                    //                    join cc in context.Common_Contact
                    //                        on er.Contact_ID equals cc.Contact_ID
                    //                    where ((er.FirstName.StartsWith(query) || er.LastName.StartsWith(query)))
                    //                    select new Registration
                    //                    {
                    //                        ID = er.Registration_ID,
                    //                        FirstName = cc.FirstName,
                    //                        LastName = cc.LastName,
                    //                        Conference_ID = er.Conference_ID,
                    //                        ConferenceName = er.ConferenceName,
                    //                        Email = (String.IsNullOrEmpty(cc.Email) ? cc.Email2 : cc.Email)

Mobile/Views/CheckIn/Collect.cshtml
@model Planetshakers.Events.Models.RegistrationViewModel

@{
Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">

    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Check In</h3>
        </div>
    </div>
</div>

<div>
    <fieldset>
        <legend>Registration Details</legend>            

        <form action="@Url.Action("Submit","CheckIn")" method="post" class="row mx-3 form-group">
            <div class="col-lg-12">
                @*<h4><strong>@Model.ConferenceName</strong></h4>*@
            </div>
            <br/>
            <div class="col-lg-6">
                Total: @Model.total_count <br /><br />
                Allocated: @Model.allocated_count <br /><br />
                Unallocated: @Model.unallocated_count <br /><br />
            </div>
            <div class="col-lg-3">
                &nbsp;&nbsp;
            </div>
            <div class="col-lg-3">

                @if (Model.Registration.ID > 0)
                {
                    <a href="@Url.Action("Allocate", "CheckIn", new { registrationId = Model.Registration.ID })" class="btn btn-primary btn-block">Force Allocate Now</a>
                }
                else
                {
                    <a href="@Url.Action("Allocate", "CheckIn", new { registrationId = Model.Registration.ID, groupleaderId = Model.Registration.GroupLeader_ID, venueId = Model.Venue_ID })" class="btn btn-primary btn-block">Force Allocate Now</a>
                }

                <a href="@Url.Action("Allocations","Administration", new { })" class="btn btn-primary btn-block">Quick Add Allocation</a>
            </div>
            <br/>
            <div class="col-lg-12">
                <table class="table table-bordered">
                    <tr class="table-active">
                        <th>Registration ID</th>
                        <th>Name</th>
                        <th>Registration Type</th>
                        <th>Outstanding Balance</th>
                        <th>Notes</th>
                    </tr>
                    @foreach (var single_reg in Model.GroupRegistration)
                    {
                         if (Model.IsCoach(single_reg))
                        {
                            <tr class="coaches">
                                <td>
                                    @if (single_reg.Attended == true)
                                    {
                                        <strong>Collected</strong>
                                    }
                                    else
                                    {
                                        <input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" />
                                        @single_reg.ID
                                    }
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                                <td>@single_reg.OutstandingBalance.ToString("0.00")</td>
                                <td>
                                    <span>Priority Seating</span><br />
                                    @if (Model.hasPlanetBusinessBreakfast(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>PlanetBusiness</span><br />
                                    }
                                    @if (Model.hasLeadershipSummit(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Leadership Summit</span>
                                    }
                                </td>
                            </tr>
                        }
                        else if (single_reg.OutstandingBalance > 0)
                        {
                            <tr class="outstanding">
                                <td>
                                    @if (single_reg.Attended == true)
                                    {
                                        <strong>Collected</strong>
                                    }
                                    else
                                    {
                                        <input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" />
                                        @single_reg.ID
                                    }
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                                <td>@single_reg.OutstandingBalance.ToString("0.00")</td>
                                <td>
                                    @if (Model.hasPlanetBusinessBreakfast(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>PlanetBusiness</span><br />
                                    }
                                    @if (Model.hasLeadershipSummit(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Leadership Summit</span><br />
                                    }
                                </td>
                            </tr>
                        }
                        else if (single_reg.RegoType.Contains("PlanetKids"))
                        {
                            <tr class="planetkids">
                                <td>
                                    @if (single_reg.Attended == true)
                                    {<strong>Collected</strong>}
                                    else
                                    {<input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" /><span> @single_reg.ID</span>}
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                                <td>@single_reg.OutstandingBalance.ToString("0.00")</td>
                                <td>
                                    @*@if (Model.hasChildEnrolmentForm(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Child Enrolment Form</span>
                                    }*@
                                    @if (Model.hasPlanetBusinessBreakfast(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>PlanetBusiness</span><br />
                                    }
                                    @if (Model.hasLeadershipSummit(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Leadership Summit</span><br />
                                    }
                                </td>
                            </tr>
                        }
                        else if (single_reg.RegoType.Contains("Deposit"))
                        {
                            <tr class="deposit">
                                <td>
                                    @if (single_reg.Attended == true)
                                    {<strong>Collected</strong>}
                                    else
                                    {<input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" /><span> @single_reg.ID</span>}
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                                <td>@single_reg.OutstandingBalance.ToString("0.00")</td>
                                <td>
                                    @if (Model.hasPlanetBusinessBreakfast(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>PlanetBusiness</span><br />
                                    }
                                    @if (Model.hasLeadershipSummit(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Leadership Summit</span><br />
                                    }
                                </td>
                            </tr>
                        }
                        else if (single_reg.RegoType.Contains("Only"))
                        {
                            <tr class="partial">
                                <td>
                                    @if (single_reg.Attended)
                                    {<strong>Collected</strong>}
                                    else
                                    {<input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" /><span> @single_reg.ID</span>}
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                                <td>@single_reg.OutstandingBalance.ToString("0.00")</td>
                                <td>
                                    @if (Model.hasPlanetBusinessBreakfast(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>PlanetBusiness</span><br />
                                    }
                                    @if (Model.hasLeadershipSummit(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Leadership Summit</span><br />
                                    }
                                </td>
                            </tr>
                        }
                        else
                        {
                            <tr class="">
                                <td>
                                    @if (single_reg.Attended == true)
                                    {<strong>Collected</strong>}
                                    else
                                    {<input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" /><span> @single_reg.ID</span>}
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                                <td>@single_reg.OutstandingBalance.ToString("0.00")</td>
                                <td>
                                    @if (Model.hasPlanetBusinessBreakfast(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>PlanetBusiness</span><br />
                                    }
                                    @if (Model.hasLeadershipSummit(single_reg))
                                    {
                                        <i class="fa fa-check"></i><span>Leadership Summit</span><br />
                                    }
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>                

            <input type="hidden" id="Contact_ID" name="Contact_ID" value="@Model.Registration.ContactID" />
            <input type="hidden" id="Venue_ID" name="Venue_ID" value="@Model.Venue_ID" />

            <div class="col-lg-12">
                <input class="checkdisplay" name='select' type="checkbox" onchange="selectAll(this)" /><strong> Select All <span id="count"></span></strong><br /><br />
                <table id="selected_collect"></table>
            </div>


            <div class="col-lg-3">
                <a href="@Url.Action("Conference", "CheckIn" )" class="btn btn-primary btn-block">Cancel</a>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-3">
                <input type="submit" value="Collect" class="btn btn-primary btn-block" />
            </div>
        </form>

    </fieldset>
</div>

Mobile/Views/CheckIn/Conference.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}


<div class="row">

    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Conference Check In</h3>
        </div>
    </div>
</div>

<!-- Check In Barcode -->
<div class="mx-3">
    <form action="@Url.Action("Collect","CheckIn")" method="post" class="row form-group">
        <div class="col-lg-8">
            <input data-val="true" data-val-required="The Barcode field is required." id="registrationid" name="registrationid" type="text" placeholder="Barcode" value="" required class="form-control" />
        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-3 my-3 my-lg-0">
            <input type="submit" value="Submit" class="btn btn-primary btn-block" />
        </div>
    </form>
    <br />

    <div class="row">
        <div class="col-lg-4 my-1 my-lg-0">
            <a href="@Url.Action("Allocation", "CheckIn" )" class="btn btn-primary btn-block">Allocate Now</a>
        </div>
        <div class="col-lg-4 my-1 my-lg-0">
            <a href="@Url.Action("Registrations", "CheckIn" )" class="btn btn-primary btn-block">View All Registrations</a>
        </div>
        <div class="col-lg-4 my-1 my-lg-0">
            <a href="@Url.Action("GroupRegistrations", "CheckIn" )" class="btn btn-primary btn-block">Search By Group</a>
        </div>
    </div>
</div>

Mobile/Views/CheckIn/GroupCollect.cshtml
@model Planetshakers.Events.Models.RegistrationViewModel

@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">

    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Group Check In</h3>
        </div>
    </div>

</div>
<div>
    <fieldset>
        <legend>Registration Details</legend>

        <form action="@Url.Action("Submit","CheckIn")" method="post" class="row mx-3 form-group">
            <div class="col-lg-6">
                <p><strong>Total:</strong> @Model.total_count</p>
                <p><strong>Allocated:</strong> @Model.allocated_count</p>
                <p><strong>Unallocated:</strong> @Model.unallocated_count</p>
            </div>

            @if (Model.Registration.ID != 0)
            {
                <div class="col-lg-3">
                    <a href="@Url.Action("Allocate", "CheckIn", new { registrationId = Model.Registration.ID })" class="btn btn-primary btn-block">Force Allocate Now</a>
                </div>
            }

            <div class="col-lg-3">
                <a href="@Url.Action("Allocations","Administration", new { })" class="btn btn-primary btn-block">Quick Add Allocation</a>
            </div>
            <br />
            <div class="col-lg-12">
                <table class="table table-bordered">
                    <tr class="table-active">
                        <th>Registration ID</th>
                        <th>Name</th>
                        <th>Registration Type</th>
                    </tr>
                    @foreach (var single_reg in Model.GroupRegistration)
                    {
                        if (single_reg.RegoType.Contains("Planetkids"))
                        {
                            <tr style="background-color:lightpink;">
                                <td>
                                    @if (single_reg.Attended == true)
                                    {<strong>Collected</strong>}
                                    else
                                    {<input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" /><span> @single_reg.ID</span>}
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td>
                                    @if (single_reg.Attended == true)
                                    {<strong>Collected</strong>}
                                    else
                                    {<input type="checkbox" name="attended" value="@single_reg.ID" class="attendance" /><span> @single_reg.ID</span>}
                                </td>
                                @{
                                    var FullName = single_reg.FirstName + " " + single_reg.LastName;
                                }
                                <td>@FullName</td>
                                <td>@single_reg.RegoType</td>
                            </tr>
                        }
                    }
                </table>
            </div>

            <input type="hidden" id="Contact_ID" name="Contact_ID" value="@Model.Registration.ContactID" />
            <input type="hidden" id="Venue_ID" name="Venue_ID" value="@Model.Venue_ID" />

            <br />
            <div class="col-lg-12">
                <input class="checkdisplay" name='select' type="checkbox" onchange="selectAll(this)" /><strong> Select All <span id="count"></span></strong><br /><br />
                <table id="selected_collect"></table>
            </div>
            <br />

            <div class="col-lg-3">
                <a href="@Url.Action("Conference", "CheckIn" )" class="btn btn-primary btn-block">Cancel</a>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-3">
                <input type="submit" value="Collect" class="btn btn-primary btn-block" />
            </div>
        </form>

    </fieldset>

</div>
    

Mobile/Views/CheckIn/NoneSelected.cshtml
@using Planetshakers.Events.Controllers;

<div>
    <div class="row mx-3">
        <div class="col-lg-12">
            <h4>You have selected none!</h4>

        </div>
        <div class="col-lg-3">
            <a href="@Url.Action("Conference", "CheckIn")" class="btn btn-primary btn-block">Continue</a>
        </div>
    </div>

</div>

Mobile/Views/CheckIn/NotInRange.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div>
    <div class="row mx-3">
        <div class="col-lg-12">
            <h6>This ID does not exist.</h6>
        </div>
        <div class="col-lg-3">
            <a href="@Url.Action("Conference", "CheckIn" )" class="btn btn-primary btn-block">Continue</a>
        </div>
    </div>
</div>

Mobile/Views/CheckIn/Registrations.cshtml
@model Planetshakers.Events.Models.RegistrationViewModel
@using Planetshakers.Core.Models;

@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<div class="row">
    <div class="col-lg-12 border-bottom">
        <div>
            <h3>Search Registrations</h3>
        </div>
    </div>

</div>

@using (Html.BeginForm("SearchRegistration", "CheckIn", FormMethod.Post, new { @class = "form-group row mx-3" }))
{
    <div class="col-lg-9">
        @Html.TextBox("query", "", new { @placeholder = "Name or Email", @class = "form-control" })
    </div>
    <div class="col-lg-3 my-3 my-lg-0">
        <input type="submit" value="Search" class="btn btn-primary btn-block" />
    </div>
}
<div>
    <div class="row mx-3">
        <div class="col-lg-12">
            @if (Model.searchList != null)
            {

                <table class="table table-bordered">
                    <tr class="table-active">
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Conference</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model.searchList)
                    {
                        <tr>
                            <td>@item.FirstName</td>
                            <td>@item.LastName</td>
                            <td>@item.Email</td>
                            <td>@item.ConferenceName</td>
                            <td><a href="@Url.Action("Collect", "CheckIn", new { registrationId = item.ID })" class="btn btn-primary btn-block" target="_blank">Check In</a></td>
                        </tr>
                    }
                </table>

            }
            else
            {
                <p><strong>No registration found.</strong></p>
            }
        </div>
    </div>

</div>