Mobile/Models/FundingGoalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Planetshakers.Events.Models
{
    public class FundingGoalViewModel
    {
        public int RegistrationType_ID { get; set; }
        public List<FundingGoal> FundingGoalList { get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var list = (from fg in context.Events_FundingGoal
                                where fg.RegistrationType_ID == RegistrationType_ID
                                orderby fg.DueDate
                                select new FundingGoal
                                {
                                    ID = fg.FundingGoal_ID,
                                    Milestone = fg.Milestone,
                                    CumulativeTotal = fg.CumulativeTotal, 
                                    DueDate = fg.DueDate,
                                    RegistrationType_ID = RegistrationType_ID
                                }).ToList();
                    return list;
                }
            }
        }       
    }
    public class FundingGoal
    {
        public int ID { get; set; }
        public int RegistrationType_ID { get; set; }
        public string Milestone { get; set; }
        public int CumulativeTotal { get; set; }
        public DateTime DueDate { get; set; }

    }

}

Mobile/Models/SignUpLink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Planetshakers.Core.Models;

namespace Planetshakers.Events.Models
{
    public class SignUpLink
    {
        public string EventName { get; set; }
        public int Event_ID { get; set; }
        public int Venue_ID { get; set; }
    }
    public class SignUpLinkViewModel
    {
        public List<SignUpLink> SignUpLinks
        {
            get
            {
                using(PlanetshakersEntities context = new PlanetshakersEntities())
                {
                    var list = (from c in context.Events_Conference
                                join v in context.Events_Venue on c.Conference_ID equals v.Conference_ID
                                where c.Visibility == true
                                select new SignUpLink
                                {
                                    EventName = c.ConferenceName,
                                    Event_ID = c.Conference_ID,
                                    Venue_ID = v.Venue_ID
                                }).ToList();
                    return list;
                }
            }
        }

    }
}

Mobile/Models/TermsAndConditionsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Planetshakers.Events.Models
{
    public class TermsAndConditionsViewModel
    {

        public int SelectedConferenceID { get; set; }
        public List<SelectListItem> event_list
        {
            get
            {
                using (PlanetshakersEntities context = new PlanetshakersEntities())
                {

                    var list = (from ec in context.Events_Conference
                                join ev in context.Events_Venue
                                    on ec.Conference_ID equals ev.Conference_ID
                                orderby ev.ConferenceStartDate descending
                                select new SelectListItem
                                {
                                    Value = ec.Conference_ID.ToString().Trim(),
                                    Text = ec.ConferenceName
                                }).ToList();

                    return list;
                }
            }
        }

    }
}

Mobile/Controllers/SetupController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mime;
using Planetshakers.Core.Models;
using Planetshakers.Events.Models;
using Planetshakers.Church.Web.vNext.Helpers;

namespace Planetshakers.Events.Controllers
{
    [Authorize]
    public class SetupController : Controller
    {
        // GET: Setup
        public ActionResult Index()
        {
            return View();
        }
        #region Registration Type
        public ActionResult RegistrationType()
        {
            RegistrationTypeViewModel newRegoTypeModel = new RegistrationTypeViewModel();
            return View(newRegoTypeModel);
        }
        public ActionResult GenerateRegistrationType(string ConferenceID)
        {
            RegistrationTypeViewModel newRegoTypeModel = new RegistrationTypeViewModel();
            newRegoTypeModel.SetRegistrationTypesList(Int32.Parse(ConferenceID));
            newRegoTypeModel.SelectedConferenceID = Int32.Parse(ConferenceID);
            newRegoTypeModel.SelectedConference = ConferenceID;
            return View("_RegistrationType", newRegoTypeModel);
        }

        [HttpPost]
        public ActionResult CheckRegoTypeName(int Conference_ID, string RegoName)
        {
            var sameName = false;
            using (PlanetshakersEntities context = new PlanetshakersEntities())
            {
                sameName = (from rt in context.Events_RegistrationType
                            where rt.Conference_ID == Conference_ID && rt.RegistrationType == RegoName
                            select rt).Any();
                return Json(new { sameName }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AddNewRegoType(string conferenceID, string regoTypeName, string regoLimit, string regoCost, string startDate,
                                           string endDate, string startTime, string endTime, string IsCollegeRego,string IsApplicationRego, string IsAddonRego, 
                                           List<int> QuestionList, List<int> DocTypeList)
        {
            Events_RegistrationType newregotype = new Events_RegistrationType
            {
                AvailableOnlineGroup = false,
                AvailableOnlineSingle = IsApplicationRego == "true" ? true : false,
                Conference_ID = Int32.Parse(conferenceID),
                EndDate = DateTime.Parse(endDate + " " + endTime),
                GroupMinimumQuantity = 1,
                IsCollegeRegistrationType = false,
                //IsCollegeRegistrationType = IsCollegeRego == "true" ? true : false,
                ApplicationRegistrationType = IsApplicationRego == "true" ? true : false,
                AddOnRegistrationType = IsAddonRego == "true" ? true : false,
                RegistrationCost = Decimal.Parse(regoCost),
                RegistrationType = regoTypeName,
                StartDate = DateTime.Parse(startDate + " " + startTime),
                Limit = Int32.Parse(regoLimit),

            };
            
            RegistrationTypeViewModel newRegoTypeModel = new RegistrationTypeViewModel();
            newRegoTypeModel.SelectedConference = conferenceID;
            newRegoTypeModel.addRegistrationType(newregotype);
            newRegoTypeModel.SetRegistrationTypesList(Int32.Parse(conferenceID));
            newRegoTypeModel.AddRTquestions(QuestionList, newregotype.RegistrationType_ID);
            newRegoTypeModel.AddRTdocs(DocTypeList, newregotype.RegistrationType_ID);



            return Json(new { });
        }

        public ActionResult EditRegoType(string conferenceID, string regoTypeID, string regoTypeName, string regoLimit,
                                        string regoCost, string startDate, string endDate, string startTime, string endTime,
                                        string IsCollegeRego, string IsApplicationRego, string IsAddonRego, 
                                        List<int> QuestionList, List<int> DocTypeList)
        {
            Events_RegistrationType editregotype = new Events_RegistrationType
            {
                RegistrationType_ID = Int32.Parse(regoTypeID),
                Conference_ID = Int32.Parse(conferenceID),
                EndDate = DateTime.Parse(endDate + " " + endTime),
                AvailableOnlineSingle = IsApplicationRego == "true" ? true : false,
                IsCollegeRegistrationType = false,
                //IsCollegeRegistrationType = IsCollegeRego == "true" ? true : false,
                ApplicationRegistrationType = IsApplicationRego == "true" ? true : false,
                AddOnRegistrationType = IsAddonRego == "true" ? true : false,
                RegistrationCost = Decimal.Parse(regoCost),
                RegistrationType = regoTypeName,
                StartDate = DateTime.Parse(startDate + " " + startTime),
                Limit = Int32.Parse(regoLimit)
            };

            RegistrationTypeViewModel newRegoTypeModel = new RegistrationTypeViewModel();
            newRegoTypeModel.SelectedConference = conferenceID;
            newRegoTypeModel.editRegistrationType(editregotype);
            newRegoTypeModel.EditRTquestions(QuestionList, editregotype.RegistrationType_ID);
            newRegoTypeModel.EditRTdocs(DocTypeList, editregotype.RegistrationType_ID);

            return Json(new
            {
                //regoID = editregotype.RegistrationType_ID,
                //startDate = editregotype.StartDate.ToString(),
                //endDate = editregotype.EndDate.ToString(),
                //regoName = editregotype.RegistrationType,
                //cost = editregotype.RegistrationCost.ToString("0.00")
            });
        }
        [HttpPost]
        public ActionResult GetQuestionAndDoc(int RegistrationType_ID)
        {
            using (PlanetshakersEntities context = new PlanetshakersEntities())
            {
                var questionList = (from aq in context.Volunteer_ApplicationQuestion
                                    where aq.Active
                                    select new Event_Question
                                    {
                                        Question_ID = aq.Question_ID,
                                        ShortName = aq.ShortName,
                                        Inactive = !(from q in context.Volunteer_EventQuestion where q.RegistrationType_ID == RegistrationType_ID && q.Question_ID == aq.Question_ID && q.Inactive == false select q).Any()
                                    }).ToList();

                var html = "";
                html += "<label>Include Questions: (Questions are referred as their short names)</label><select name='selValue' id='QuestionSelected_" + RegistrationType_ID+"' class='form-control' multiple='multiple' data-live-search='true' data-style='multi-select-btn'>";
                foreach (var question in questionList)
                {
                    if (question.Inactive)
                    {

                        html += "<option value = '" + question.Question_ID + "' >" + question.ShortName + "</option > ";
                    }
                    else
                    {
                        html += "<option value = '" + question.Question_ID + "' selected>" + question.ShortName + "</option > ";
                    }
                }
                html += "</select><br />";


                var docList = (from aq in context.Volunteer_DocumentType
                               where aq.Active
                               select new Event_Doc
                               {
                                   Doc_ID = aq.DocumentType_ID,
                                   Name = aq.DocumentType,
                                   Inactive = !(from q in context.Volunteer_EventDocument where q.RegistrationType_ID == RegistrationType_ID && q.DocumentType_ID == aq.DocumentType_ID && q.Inactive == false select q).Any()
                               }).ToList();


                var html2 = "";
                html2 += "<label>Include Document Type: </label><select name='selValue' id='DocSelected_" + RegistrationType_ID + "' class='form-control' multiple='multiple' data-live-search='true' data-style='multi-select-btn'>";
                foreach (var question in docList)
                {
                    if (question.Inactive)
                    {

                        html2 += "<option value = '" + question.Doc_ID + "' >" + question.Name + "</option > ";
                    }
                    else
                    {
                        html2 += "<option value = '" + question.Doc_ID + "' selected>" + question.Name + "</option > ";
                    }
                }
                html2 += "</select><br />";


                return Json(new { question = html, doc = html2 });
            }
        }

        public ActionResult DeleteRegoType(string regoTypeID)
        {
            int regotypeid = Int32.Parse(regoTypeID);
            RegistrationTypeViewModel newRegoTypeModel = new RegistrationTypeViewModel();
            bool success = newRegoTypeModel.deleteRegoType(regotypeid);

            return Json(new { success });
        }
        [HttpPost]
        public ActionResult SortRegistrationType(List<SortOrderItem> RegistrationTypeList)
        {
            string success = "Registration Type order saved successfully.";
            SortOrderModel model = new SortOrderModel();
            model.SortRegistrationType(RegistrationTypeList);
            return Json(new { resultmessage = success }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Funding Goals
        public ActionResult OpenFundingGoalModel(int RegistrationType_ID)
        {
            FundingGoalViewModel model = new FundingGoalViewModel();
            model.RegistrationType_ID = RegistrationType_ID;

Mobile/Views/Setup/BulkChangeRegistrationType.cshtml
@using System.Data;
@model Planetshakers.Events.Models.BulkChangeRegoTypeViewModel
@{
    ViewBag.Title = "Bulk Transfer Conference Registration Type";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.setup.js")"></script>

<div class="row">

    <div class="col-lg-12 border-bottom expanded">
        <h3>@ViewBag.Title</h3>
    </div>
</div>
@if (Model.Transferred)
{
    <div class="row mx-3">
        <div class="col-12">
            <div class="alert alert-success">
                <strong>Successfully transferred all registration to selected registration type.</strong>
            </div>
        </div>
    </div>
}
<div class="row mx-3">
    <div class="col-12">
        <h3>Selected Conference:</h3>
        <div class="card">
            <div class="card-body shadow">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Date</th>
                            <th>Location</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.selectedConference.ConferenceName</td>
                            <td>@Model.selectedConference.ConferenceDate</td>
                            <td>@Model.selectedConference.ConferenceLocation</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@if (Model.selectedRegistrationType != null)
{
    <div class="row mx-3 my-4">
        <div class="col-12">
            <h3>Change all registrations' registration type from:</h3>
            <div class="card">
                <div class="card-body shadow">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Cost</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>@Model.selectedRegistrationType.RegistrationType</td>
                                <td>@Model.selectedRegistrationType.RegistrationCost.ToString("0.00")</td>
                                <td>@Model.selectedRegistrationType.StartDate.ToString("yyyy-MM-dd")</td>
                                <td>@Model.selectedRegistrationType.EndDate.ToString("yyyy-MM-dd")</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<div class="row mx-3 my-4">
    <div class="col-12">
        <h3>Transfer all registrations' registration type from:</h3>
        <div class="card">
            <div class="card-body shadow">
                @using (Html.BeginForm("GenerateRegistrations", "Setup", FormMethod.Post, new { id = "generateRegoForm" }))
                {
                    <div class="row">
                        <div class="col-9">
                            @Html.HiddenFor(x => Model.selectedConferenceID)
                            @Html.DropDownListFor(x => x.selectedRegistrationTypeID, Model.availableRegistrationTypeList, new { @class = "form-control" })
                        </div>
                        <div class="col-3">
                            <button class="btn btn-primary" type="submit" id="">Generate Registrations</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

</div>

@if (Model.selectedRegistrationType != null && Model.Transferred == false)
{
    <div class="row mx-3 my-4">
        <div class="col-12">
            <h3>Transfer all registrations' registration type to:</h3>
            <div class="card">
                <div class="card-body shadow">
                    @using (Html.BeginForm("TransferBulkRego", "Setup", FormMethod.Post, new { id = "checkInReportForm" }))
                    {
                        <div class="row">
                            <div class="col-9">
                                @Html.HiddenFor(x => Model.selectedConferenceID)
                                @Html.HiddenFor(x => Model.selectedRegistrationTypeID)
                                @Html.DropDownListFor(x => x.newRegistrationTypeID, Model.availableRegistrationTypeList, new { @class = "form-control" })
                            </div>
                            <div class="col-3">
                                <button class="btn btn-warning" type="button" id="transferBtn" data-toggle="modal" data-target="#transferConfirmation">Transfer</button>
                                <div class="modal fade" id="transferConfirmation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h3 class="modal-title">Transfer Confirmation</h3>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure to transfer all registrations' registration type? (This action is irreversible.)
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Transfer</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

@if (Model.selectedRegistrationType != null && Model.Transferred == false)
{
    <div class="row mx-3 my-4">
        <div class="col-12">
            <h3>All registrations in "@Model.selectedRegistrationType.RegistrationType" registration type:</h3>
            <div class="card">
                <div class="card-body shadow">
                    <table class="table table-bordered" id="BulkRegoTransferTable">
                        <thead>
                            <tr>
                                <th>Contact ID</th>
                                <th>Full Name</th>
                                <th>Registration Date</th>
                                <th>Attended</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var rego in Model.registrationList)
                            {
                                <tr>
                                    <td>@rego.ContactID</td>
                                    <td>@rego.FirstName @rego.LastName</td>
                                    <td>@rego.RegistrationDate.ToString("yyyy-MM-dd")</td>
                                    <td>
                                        @if (rego.Attended)
                                        {
                                            <i class="fa fa-check"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-times"></i>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<div class="row mx-3 my-4">
    <div class="col-12">
        <button class="btn btn-primary" onclick="window.location.href='/Setup/RegistrationType'">Back to registration type</button>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        if ($("#BulkRegoTransferTable").length > 0) {
            if (!$.fn.DataTable.isDataTable('#BulkRegoTransferTable')) {
                $('#BulkRegoTransferTable').DataTable({
                    fixedHeader: {
                        header: true,
                        footer: true
                    },
                    "bPaginate": false,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "autoWidth": false,
                    "aaSorting": [],
                    scrollCollapse: true,
                    responsive: true,
                    paging: true,
                    language: {
                        search: "",
                        searchPlaceholder: "Search..."
                    }
                });
            }
        }

    });
</script>

Mobile/Views/Setup/Conference.cshtml
@using System.Data;
@model Planetshakers.Events.Models.ConferenceViewModel
@{
    ViewBag.Title = "Trip Set Up";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
<script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.setup.js")"></script>

<div class="row">

    <div class="col-lg-12 border-bottom expanded">
        <h3>@ViewBag.Title</h3>
    </div>
</div>
<div>
    <div class="row mx-3">
        <div id="conferenceCheck" class="col-lg-12" style="display: none;">
            <div class="alert alert-danger fa-border"><strong>Please select a trip.</strong></div><br />
        </div>
        <div class="col-lg-9">
            <form class="form-group">
                <!-- select conference or event.-->
                <label>Trips:</label><br />
                @Html.DropDownListFor(m => m.SelectedConference, Model.event_list,
               "-- Select Trip --", new { required = "required", id = "selectedConference", @class="form-control" })
            </form>

        </div>
        
        <div class="col-lg-3 py-0 py-lg-4">
            <button class="btn btn-primary btn-block" onclick="generateConfDeets()" style="margin: 0px;">Select</button>
        </div>
        <div class="col-lg-3 py-2 py-lg-0">
            <button class="btn btn-primary btn-block" type="button" onclick="addConference()">Add New Trip</button>
        </div>
        <div id="conferenceViewResult" class="col-lg-12"></div>
        
        <div class="col-lg-9"></div>
    </div>
</div>

Mobile/Views/Setup/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<h2>Index</h2>

Mobile/Views/Setup/RegistrationType.cshtml
@using System.Data;
@model Planetshakers.Events.Models.RegistrationTypeViewModel
@{
    ViewBag.Title = "Registration Type";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@*<script type="text/javascript" src="@Url.Content("~/Scripts/planetshakers.events.setup.js")"></script>*@

<div class="row">

    <div class="col-lg-12 border-bottom">
        <h3>@ViewBag.Title</h3>
    </div>

</div>

<div>
    <div class="row mx-3 form-group">
        <div id="conferenceCheck" class="col-lg-12" style="display: none;">
            <div class="alert alert-danger fa-border"><strong>Please select a conference.</strong></div><br />
        </div>

        <div class="col-lg-9">
            <!-- select conference or event.-->
            <label>Trip:</label>
            @Html.DropDownListFor(m => m.SelectedConference, Model.event_list, "-- Select Trip --", new { required = "required", id = "selectedConference", @class = "form-control" })
        </div>
        <div class="col-lg-3" style="padding-top: 10px;">
            <button class="btn btn-primary my-3" onclick="generateRegotype()">Select</button>
        </div>
        <br />
        <div class="col-lg-12" id="addRegoTypeSuccess" style="display: none;">
            <div class="alert alert-success fa-border"><strong> Successfully added Registration Type.</strong><br /></div>
        </div>
        <div class="col-lg-12"  style="display: none;" id="editRegoSuccess">
            <div class="alert alert-success fa-border"><strong>Successfully edited Registration Type.</strong><br /></div>
        </div>
        <div id="regoTypeViewResult" class="col-lg-12"></div>

    </div>
    
</div>
        

Mobile/Views/Setup/SignUpLinks.cshtml
@model Planetshakers.Events.Models.SignUpLinkViewModel
@{
    ViewBag.Title = "Trip Sign Up Links";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}


<div class="row mb-4">

    <div class="col-lg-12 border-bottom expanded">
        <h3>@ViewBag.Title</h3>
    </div>
    <div class="col-lg-12">
        <br />
        <h5>Sign Up link for each trip</h5><br />
        <div classs="card">
            <div class="card card-body">
                <table id="ConferenceTable" class="table table-bordered" width="100%">
                    <thead>
                        <tr>
                            <th>Trip Name</th>
                            <th>Link</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var conf in Model.SignUpLinks)
                        {
                            <tr id="@conf.Event_ID">
                                <td>@conf.EventName</td>
                                <td>@Html.TextBox("url_" + conf.Event_ID, "missions.believeglobal.org/Events/Register/" + conf.Venue_ID, new { @class = "form-control", disabled = "disabled" })</td>
                                <td><button class="btn btn-primary" onclick="copyToClipboard(@conf.Event_ID)">Copy Link</button></td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    function copyToClipboard(Event_ID) {
        var str = $("#url_" + Event_ID).val()
        return new Promise(function (resolve, reject) {
            var success = false;
            function listener(e) {
                e.clipboardData.setData("text/plain", str);
                e.preventDefault();
                success = true;
            }
            document.addEventListener("copy", listener);
            document.execCommand("copy");
            document.removeEventListener("copy", listener);
            success ? resolve() : reject();
            alert("Copied link")
        });
    };
</script>

Mobile/Views/Setup/SortOrder.cshtml
@model Planetshakers.Events.Models.SortOrderModel
@{
    ViewBag.Title = "Sort Trip";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}


<div class="row mb-4">

    <div class="col-lg-12 border-bottom expanded">
        <h3>@ViewBag.Title</h3>
    </div>
    <div class="col-lg-12">
        <br />
        <h5>Trips that appears on missions.believeglobal.org</h5>
        <h5>Please drag and drop trip item to re-order them.</h5><br />
        <div classs="card">
            <div class="card card-body">
                <table id="sortConferenceTable" class="table table-bordered" width="100%">
                    <thead>
                        <tr><th>Trip</th></tr>
                    </thead>
                    <tbody>
                        @foreach (var conf in Model.conf_list)
                        {
                            <tr id="@conf.Conference_ID"><td>@conf.ConferenceName</td></tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-9"></div>
    <div class="col-lg-3"><button class="btn btn-primary btn-block" onclick="sortOrder()">Save Order</button></div>
</div>